# Settings
# Invincibility lasts for so and so seconds
Invincibility: 120
# Feast size
FeastSize: 20
# When does the feast happen? (20min by default)
TimeTillFeast: 1200
# How many layers high are the chests?
ChestLayers: 3
# Chest size
# Can spectators talk to live players, by default OP's can.
SpectatorChat: false
# Are there spectators. Permission to bypass is Hungergames.Spectate
Spectators: true
# Does the game kick them when they die?
KickOnDeath: false
# Should mushroom stew be enabled? This is instant eat for hunger or health regains
MushroomStew: false
MushroomStewRestores: 6

# What command to stop the server?
StopServerCommand: stop

# Shall players fly pregame?
FlyPregame: true


# Should the plugin use the mysql database?
UseMySql: false

# And setup connection details here.
MySqlUser: root
MySqlPass: password
MySqlDatabase: database
MySqlUrl: 127.0.0.1

# How much should the player get for winning
# Keep this up for as long as you like. Such as Winner666: 3
# Means if there is a player who came '666' he gets this.
Winner1: 10
Winner2: 5
Winner3: 3

# Use scoreboards
Scoreboards: true

# Display the messages scoreboards replace
Messages: true

#Removes the end and nether
RemoveEnd: true
RemoveNether: true
# Changes the spawn radius in server.properties so people can build there
ChangeSpawnLimit: true

# Disables fire spread before the game starts
DisableFireSpread: false

# Min players to start a game
MinPlayers: 2

# Delay in seconds between broadcasts of 'libraryaddict won!'
WinnerBroadcastingDelay: 6

# Delay in seconds before the game shuts down after a winner
GameShutdownDelay: 33

# Enables the kit selector
EnableKitSelector: true

# Change the kit selector, Its MATERIAL/ID DATA_VALUE
KitSelectorIcon: FEATHER 0

# Does the size if the kit selector inventory change according to the space required?
# This still takes max inventory size as set below into consideration
KitSelectorDynamicSize: false

# If false. Then whats the max size of the inventory?
# Try keep it in a multiple of 9. I'll fix it if it isn't however.
KitSelectorInventorySize: 54

# What item is the button to go forward for the kit selector
KitSelectorForward: SUGAR_CANE_BLOCK 0

# What item is the button to go Back for the kit selector
KitSelectorBack: SUGAR_CANE_BLOCK 0

# What item is the button to go forward for the spectator selector
SpectatorInventoryForward: SUGAR_CANE_BLOCK 0

# What item is the button to go Back for the spectator selector
SpectatorInventoryBack: SUGAR_CANE_BLOCK 0

# If false. Then whats the max size of the inventory?
# Try keep it in a multiple of 9. I'll fix it if it isn't however.
SpectatorSelectorInventorySize: 54

# ID of the feast, Its MATERIAL/ID DATA_VALUE
FeastGround: QUARTZ_BLOCK 0
Feast: QUARTZ_BLOCK 1
FeastInsides: TNT 0
# If the feast insides is tnt, Then the top block is changed into TNT which ignites when punched
FeastTnt: true

# Does it generate pillars under it if it can?
Pillars: true

# What time does the game start at?
Countdown: 270

# ID of pillars corners
PillarCorner: QUARTZ_BLOCK 2
# ID of material inside
PillarInsides: GLASS 0

# Change the build height limit to 128?
ChangeHeightLimit: true

# Force cords? Means the map center is always here. Nice for people when they use F3
# This changes the worlds spawn
ForceCords: true
ForceX: 0
ForceZ: 0

# You know when you press tab, it displays the kills next to the name?
# Some people have names which are too long. The plugin shortens them.
ShortenNames: true

# Some people want to have their kit name display as a prefix.
# So I'll let you change the prefixes for the game..

# Add the below options to ensure no one has problems..
# Seriously. Gonna have to move some of these options out someday.

ChangeAlivePrefix: true
ChangeSpectatingPrefix: true

# Prefix when they havn't died.
AlivePrefix: '<%Name%> %Message%'
# AlivePrefix: '&6[&r%Kit%&6]&r %Name%: %Message%'

# Prefix for when they have died.
SpectatingPrefix: '&8<&7%Name%&8>&r %Message%'
# SpectatingPrefix: '&8[&r%Kit%&8]&r &7%Name%&r: %Message%'

# Are the spectators unable to know where each other are?
InvisibleSpectators: false

# Chance out of ? of animals spawning
# Used for limiting mob spawns to raise the difficulty
# Set to 1 to make it 100%
MobSpawnChance: 5

# Check for a update and notifys anyone with the permission hungergames.update
CheckUpdates: true

# Uncomment this to use it.

#CommandsToRunBeforeShutdown:
#  - 'kick libraryaddict You smell'
#  - 'kick minecraftchick You suck'
#  - 'say Attention all: libraryaddict loves you'

# This is to disable metrics. Please dont..

DisableMetrics: false